services:
  myapp:
    build: .
    ports:
      - "80:5000"
    env_file:
      - .env
    depends_on:
      chatbot-mysql-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    entrypoint: /opt/app/entrypoint.sh 

  chatbot-mysql-db:
    container_name: chatbot-mysql-db
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--skip-name-resolve"
    ]
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
