name: Build container (REUSABLE)

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string
      TAG:
        required: true
        type: string
      DOCKERFILE:
        required: false
        type: string
        default: Dockerfile
      CONTEXT:
        required: false
        type: string
        default: .
      CACHE:
        required: true
        type: boolean
    secrets:
      PRIVATE_REGISTRY_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: bunkerity
          password: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      # Build non-cached
      - name: Build image (no cache)
        if: inputs.CACHE != true
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKERFILE }}
          load: true
          tags: local/${{ inputs.IMAGE }}
          cache-to: type=registry,ref=bunkerity/${{ inputs.IMAGE }}:${{ inputs.TAG }}-cache,mode=min
      # Build cached
      - name: Build image (with cache)
        if: inputs.CACHE == true
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKERFILE }}
          load: true
          tags: local/${{ inputs.IMAGE }}
          cache-from: type=registry,ref=bunkerity/${{ inputs.IMAGE }}:${{ inputs.TAG }}-cache
          cache-to: type=registry,ref=bunkerity/${{ inputs.IMAGE }}:${{ inputs.TAG }}-cache,mode=min
      # Check OS vulnerabilities
      - name: Check OS vulnerabilities
        uses: aquasecurity/trivy-action@69cbbc0cbbf6a2b0bab8dcf0e9f2d7ead08e87e4 # master
        with:
          vuln-type: os
          image-ref: local/${{ inputs.IMAGE }}
          format: table
          exit-code: 1
          ignore-unfixed: false
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          trivyignores: .trivyignore
