name: Deploy (REUSABLE)

on:
  workflow_call:
    inputs:
      NAMESPACE:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: k8s login
        uses: azure/k8s-set-context@38d6bc72e5877b8eb640e995218d42b8fedf1a47 # v3.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: set namespace
        run: kubectl config set-context --current --namespace=${{ inputs.NAMESPACE }}
      # Deploy website
      - name: k8s deploy chatbot
        run: kubectl rollout restart deployment www-chatbot